/*
 * SpectX API
 * SpectX REST API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@spectx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spectx.apiClientExample.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExecuteAsyncResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-23T21:09:27.694+02:00")
public class ExecuteAsyncResponse {
  @JsonProperty("queryId")
  private UUID queryId = null;

  public ExecuteAsyncResponse queryId(UUID queryId) {
    this.queryId = queryId;
    return this;
  }

   /**
   * Get queryId
   * @return queryId
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getQueryId() {
    return queryId;
  }

  public void setQueryId(UUID queryId) {
    this.queryId = queryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteAsyncResponse executeAsyncResponse = (ExecuteAsyncResponse) o;
    return Objects.equals(this.queryId, executeAsyncResponse.queryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteAsyncResponse {\n");
    
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

