/*
 * SpectX API
 * SpectX REST API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@spectx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spectx.apiClientExample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.spectx.apiClientExample.model.State;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * StateChange
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-23T21:09:27.694+02:00")
public class StateChange {
  @JsonProperty("millis")
  private Long millis = null;

  @JsonProperty("from")
  private State from = null;

  @JsonProperty("to")
  private State to = null;

  public StateChange millis(Long millis) {
    this.millis = millis;
    return this;
  }

   /**
   * Get millis
   * @return millis
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getMillis() {
    return millis;
  }

  public void setMillis(Long millis) {
    this.millis = millis;
  }

  public StateChange from(State from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(required = true, value = "")
  public State getFrom() {
    return from;
  }

  public void setFrom(State from) {
    this.from = from;
  }

  public StateChange to(State to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(required = true, value = "")
  public State getTo() {
    return to;
  }

  public void setTo(State to) {
    this.to = to;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StateChange stateChange = (StateChange) o;
    return Objects.equals(this.millis, stateChange.millis) &&
        Objects.equals(this.from, stateChange.from) &&
        Objects.equals(this.to, stateChange.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(millis, from, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StateChange {\n");
    
    sb.append("    millis: ").append(toIndentedString(millis)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

